apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-argo
  template:
    metadata:
      labels:
        app: test-argo
    spec:
      containers:
        - name: test-argo
          image: kosukefuchi/test-python:latest
          ports:
            - containerPort: 80
